window.PORTFOLIO_DATA = {
 "generated_at": "2026-08-23T07:02:25Z",
 "user": {
  "login": "sunbinbin1991",
  "name": "Binbin sun",
  "bio": "Stay foolish stay hungry ",
  "company": "",
  "location": "Hangzhou,China,Mars",
  "blog": "https://sunbinbin1991.github.io/ ",
  "followers": 36,
  "following": 205,
  "public_repos": 66,
  "created_at": "2015-10-27T12:38:05Z",
  "joined_year": 2015,
  "avatar_url": "https://avatars.githubusercontent.com/u/15342883?v=4",
  "html_url": "https://github.com/sunbinbin1991"
 },
 "stats": {
  "total": 66,
  "original": 21,
  "forks": 45,
  "total_stars": 32,
  "total_forks": 10,
  "languages": {
   "C++": 15,
   "Python": 7,
   "JavaScript": 3,
   "C#": 3,
   "TypeScript": 2,
   "CSS": 2,
   "Java": 2,
   "C": 1,
   "Matlab": 1,
   "Makefile": 1,
   "HTML": 1,
   "Jupyter Notebook": 1
  },
  "top_original": [
   {
    "name": "faceTracker",
    "description": "Open-source face tracking for beginners · faceTracker 入门级人脸跟踪",
    "html_url": "https://github.com/sunbinbin1991/faceTracker",
    "homepage": "",
    "language": "C",
    "stars": 6,
    "forks": 1,
    "topics": [],
    "created_at": "2019-10-27T16:52:55Z",
    "updated_at": "2026-08-21T08:28:49Z",
    "fork": false,
    "archived": false,
    "is_profile": false
   },
   {
    "name": "yinyangFace",
    "description": "Yin-yang face (uneven lighting) quality detection · 阴阳脸检测",
    "html_url": "https://github.com/sunbinbin1991/yinyangFace",
    "homepage": "",
    "language": "Python",
    "stars": 5,
    "forks": 1,
    "topics": [],
    "created_at": "2018-10-30T07:53:14Z",
    "updated_at": "2026-08-21T08:28:44Z",
    "fork": false,
    "archived": false,
    "is_profile": false
   },
   {
    "name": "detect",
    "description": "Face detection demo with dlib (Python)",
    "html_url": "https://github.com/sunbinbin1991/detect",
    "homepage": "",
    "language": "Python",
    "stars": 4,
    "forks": 2,
    "topics": [],
    "created_at": "2017-07-20T12:28:43Z",
    "updated_at": "2026-08-21T08:28:35Z",
    "fork": false,
    "archived": false,
    "is_profile": false
   },
   {
    "name": "cublas",
    "description": "cublas计算加速",
    "html_url": "https://github.com/sunbinbin1991/cublas",
    "homepage": "",
    "language": "C++",
    "stars": 3,
    "forks": 0,
    "topics": [],
    "created_at": "2018-07-09T13:00:12Z",
    "updated_at": "2022-08-08T15:26:17Z",
    "fork": false,
    "archived": false,
    "is_profile": false
   },
   {
    "name": "Des-Encrypt",
    "description": "一个简单的加密算法",
    "html_url": "https://github.com/sunbinbin1991/Des-Encrypt",
    "homepage": "",
    "language": "C++",
    "stars": 3,
    "forks": 1,
    "topics": [],
    "created_at": "2018-04-13T15:53:07Z",
    "updated_at": "2022-04-05T18:09:42Z",
    "fork": false,
    "archived": false,
    "is_profile": false
   },
   {
    "name": "logo-detect",
    "description": "TV logo-detect",
    "html_url": "https://github.com/sunbinbin1991/logo-detect",
    "homepage": "",
    "language": "Python",
    "stars": 3,
    "forks": 2,
    "topics": [],
    "created_at": "2017-07-26T13:16:10Z",
    "updated_at": "2020-04-24T07:42:03Z",
    "fork": false,
    "archived": false,
    "is_profile": false
   }
  ]
 },
 "events": [
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:13:30Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:44:04Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:44:00Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:38:50Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:13:05Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:12:27Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:04:59Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:44:14Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:12:40Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:13:17Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:12:53Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:03:56Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:44:09Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:44:11Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:28:27Z",
   "text": "推送 1 个提交到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:28:29Z",
   "text": "推送了代码到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "WatchEvent",
   "repo": "xugaopeng1/awesome-python-login-model",
   "repo_url": "https://github.com/xugaopeng1/awesome-python-login-model",
   "created_at": "2026-08-21T09:36:53Z",
   "text": "Star 了 xugaopeng1/awesome-python-login-model"
  },
  {
   "type": "WatchEvent",
   "repo": "QwenLM/Qwen3.8",
   "repo_url": "https://github.com/QwenLM/Qwen3.8",
   "created_at": "2026-08-21T09:22:44Z",
   "text": "Star 了 QwenLM/Qwen3.8"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:04:35Z",
   "text": "推送了代码到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:04:09Z",
   "text": "推送了代码到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:04:47Z",
   "text": "推送了代码到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T09:04:23Z",
   "text": "推送了代码到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:44:07Z",
   "text": "推送了代码到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "ForkEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:31:55Z",
   "text": "Fork 了 sunbinbin1991/sunbinbin1991.github.io"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-21T08:28:33Z",
   "text": "推送了代码到 sunbinbin1991/sunbinbin1991.github.io @ main"
  },
  {
   "type": "WatchEvent",
   "repo": "AdamPlatin123/awesome-dsh-plugins",
   "repo_url": "https://github.com/AdamPlatin123/awesome-dsh-plugins",
   "created_at": "2026-08-21T08:22:25Z",
   "text": "Star 了 AdamPlatin123/awesome-dsh-plugins"
  },
  {
   "type": "WatchEvent",
   "repo": "hikariming/dshfind",
   "repo_url": "https://github.com/hikariming/dshfind",
   "created_at": "2026-08-21T08:21:42Z",
   "text": "Star 了 hikariming/dshfind"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/deepseek-harness",
   "repo_url": "https://github.com/sunbinbin1991/deepseek-harness",
   "created_at": "2026-08-20T05:48:14Z",
   "text": "推送了代码到 sunbinbin1991/deepseek-harness @ master"
  },
  {
   "type": "PushEvent",
   "repo": "sunbinbin1991/sunbinbin1991",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991",
   "created_at": "2026-08-20T03:37:32Z",
   "text": "推送了代码到 sunbinbin1991/sunbinbin1991 @ main"
  },
  {
   "type": "WatchEvent",
   "repo": "sunbinbin1991/sunbinbin1991.github.io",
   "repo_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "created_at": "2026-08-20T03:29:07Z",
   "text": "Star 了 sunbinbin1991/sunbinbin1991.github.io"
  }
 ],
 "starred": [
  {
   "name": "awesome-python-login-model",
   "owner": "xugaopeng1",
   "full_name": "xugaopeng1/awesome-python-login-model",
   "description": "😮python模拟登陆一些大型网站，还有一些简单的爬虫，希望对你们有所帮助❤️，如果喜欢记得给个star哦🌟",
   "html_url": "https://github.com/xugaopeng1/awesome-python-login-model",
   "language": "Python",
   "stars": 2
  },
  {
   "name": "Qwen3.8",
   "owner": "QwenLM",
   "full_name": "QwenLM/Qwen3.8",
   "description": "Qwen3.8 is the large language model series developed by Qwen team, Alibaba Group.",
   "html_url": "https://github.com/QwenLM/Qwen3.8",
   "language": "",
   "stars": 3924
  },
  {
   "name": "awesome-dsh-plugins",
   "owner": "AdamPlatin123",
   "full_name": "AdamPlatin123/awesome-dsh-plugins",
   "description": "DSH 插件雷达与精选榜：多路自动发现 9000+ 候选，容器真实安装路径运行级实测（四档判定），精选 Top 50 · 11 类人工策展，全量索引 PLUGINS-ALL.md，自动更新。",
   "html_url": "https://github.com/AdamPlatin123/awesome-dsh-plugins",
   "language": "Python",
   "stars": 1342
  },
  {
   "name": "dshfind",
   "owner": "hikariming",
   "full_name": "hikariming/dshfind",
   "description": "DSH (DeepSeek Harness) 原理学习、插件市场与最佳实践 · Learn DSH principles, plugin marketplace & best practices",
   "html_url": "https://github.com/hikariming/dshfind",
   "language": "TypeScript",
   "stars": 207
  },
  {
   "name": "sunbinbin1991.github.io",
   "owner": "sunbinbin1991",
   "full_name": "sunbinbin1991/sunbinbin1991.github.io",
   "description": "Auto-generated GitHub portfolio site · Pages + Actions + API 自动生成个人 GitHub 项目汇总页（定时刷新 · 实时拉取 · 限流回退）",
   "html_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "language": "JavaScript",
   "stars": 2
  },
  {
   "name": "awesome-dsh-plugin",
   "owner": "awesome-dsh-plugin",
   "full_name": "awesome-dsh-plugin/awesome-dsh-plugin",
   "description": "A curated list of plugins for DeepSeek Harness (dsh) · DeepSeek Harness 插件精选列表",
   "html_url": "https://github.com/awesome-dsh-plugin/awesome-dsh-plugin",
   "language": "Python",
   "stars": 11627
  },
  {
   "name": "little-book-rl",
   "owner": "alxndrTL",
   "full_name": "alxndrTL/little-book-rl",
   "description": "The Little Book of Reinforcement Learning",
   "html_url": "https://github.com/alxndrTL/little-book-rl",
   "language": "Python",
   "stars": 1542
  },
  {
   "name": "archify",
   "owner": "tt-a1i",
   "full_name": "tt-a1i/archify",
   "description": "Agent skill for beautiful, verifiable architecture, workflow, sequence, data-flow, and lifecycle diagrams—self-contained HTML with motion and crisp export.",
   "html_url": "https://github.com/tt-a1i/archify",
   "language": "HTML",
   "stars": 15084
  },
  {
   "name": "awesome-zhuiju-free",
   "owner": "laoma2053",
   "full_name": "laoma2053/awesome-zhuiju-free",
   "description": "免费无广告的追剧资源指南，人工精选资源、每天检测资源有效性。收录在线影视、影视APP、网盘搜索、磁力BT、字幕、TVBox / 影视仓空壳软件/配置地址、IPTV直播源、会员拼团、影视相关开源项目。开源，社区共同维护。",
   "html_url": "https://github.com/laoma2053/awesome-zhuiju-free",
   "language": "JavaScript",
   "stars": 6122
  },
  {
   "name": "deepseek-harness",
   "owner": "deepseek-ai",
   "full_name": "deepseek-ai/deepseek-harness",
   "description": "DeepSeek Harness: Everything is a Plugin.",
   "html_url": "https://github.com/deepseek-ai/deepseek-harness",
   "language": "TypeScript",
   "stars": 185914
  },
  {
   "name": "HD-Loss",
   "owner": "lisaGUZZI",
   "full_name": "lisaGUZZI/HD-Loss",
   "description": "",
   "html_url": "https://github.com/lisaGUZZI/HD-Loss",
   "language": "Python",
   "stars": 3
  },
  {
   "name": "UNetPlusPlus",
   "owner": "MrGiovanni",
   "full_name": "MrGiovanni/UNetPlusPlus",
   "description": "[IEEE TMI Best Paper Award] Official Implementation for UNet++",
   "html_url": "https://github.com/MrGiovanni/UNetPlusPlus",
   "language": "Python",
   "stars": 2679
  },
  {
   "name": "boundary-loss",
   "owner": "LIVIAETS",
   "full_name": "LIVIAETS/boundary-loss",
   "description": "Official code for \"Boundary loss for highly unbalanced segmentation\", runner-up for best paper award at MIDL 2019. Extended version in MedIA, volume 67, January 2021.",
   "html_url": "https://github.com/LIVIAETS/boundary-loss",
   "language": "Python",
   "stars": 732
  },
  {
   "name": "DiffOPC",
   "owner": "NVlabs",
   "full_name": "NVlabs/DiffOPC",
   "description": "Differentiable Edge-Based OPC",
   "html_url": "https://github.com/NVlabs/DiffOPC",
   "language": "Python",
   "stars": 8
  },
  {
   "name": "Pytorch-UNet",
   "owner": "milesial",
   "full_name": "milesial/Pytorch-UNet",
   "description": "PyTorch implementation of the U-Net for image semantic segmentation with high quality images",
   "html_url": "https://github.com/milesial/Pytorch-UNet",
   "language": "Python",
   "stars": 11605
  },
  {
   "name": "FasterNet",
   "owner": "JierunChen",
   "full_name": "JierunChen/FasterNet",
   "description": "[CVPR 2023] Code for PConv and FasterNet",
   "html_url": "https://github.com/JierunChen/FasterNet",
   "language": "Python",
   "stars": 837
  },
  {
   "name": "Qwen3-Coder",
   "owner": "QwenLM",
   "full_name": "QwenLM/Qwen3-Coder",
   "description": "Qwen3-Coder is the code version of Qwen3, the large language model series developed by Qwen team.",
   "html_url": "https://github.com/QwenLM/Qwen3-Coder",
   "language": "Python",
   "stars": 16808
  },
  {
   "name": "agents-course",
   "owner": "huggingface",
   "full_name": "huggingface/agents-course",
   "description": "This repository contains the Hugging Face Agents Course.",
   "html_url": "https://github.com/huggingface/agents-course",
   "language": "MDX",
   "stars": 31274
  },
  {
   "name": "pytorch",
   "owner": "pytorch",
   "full_name": "pytorch/pytorch",
   "description": "Tensors and Dynamic neural networks in Python with strong GPU acceleration",
   "html_url": "https://github.com/pytorch/pytorch",
   "language": "Python",
   "stars": 102551
  },
  {
   "name": "openvino",
   "owner": "openvinotoolkit",
   "full_name": "openvinotoolkit/openvino",
   "description": "OpenVINO™ is an open source toolkit for optimizing and deploying AI inference",
   "html_url": "https://github.com/openvinotoolkit/openvino",
   "language": "C++",
   "stars": 10697
  },
  {
   "name": "openvino_notebooks",
   "owner": "openvinotoolkit",
   "full_name": "openvinotoolkit/openvino_notebooks",
   "description": "📚 Jupyter notebook tutorials for OpenVINO™",
   "html_url": "https://github.com/openvinotoolkit/openvino_notebooks",
   "language": "Jupyter Notebook",
   "stars": 3204
  },
  {
   "name": "UNeXt-pytorch",
   "owner": "jeya-maria-jose",
   "full_name": "jeya-maria-jose/UNeXt-pytorch",
   "description": "Official Pytorch Code base for \"UNeXt: MLP-based Rapid Medical Image Segmentation Network\", MICCAI 2022",
   "html_url": "https://github.com/jeya-maria-jose/UNeXt-pytorch",
   "language": "Python",
   "stars": 571
  },
  {
   "name": "Understand-Anything",
   "owner": "Egonex-AI",
   "full_name": "Egonex-AI/Understand-Anything",
   "description": "Graphs that teach > graphs that impress. Turn any code into an interactive knowledge graph you can explore, search, and ask questions about. Works with Claude Code, Codex, Cursor, Copilot, Gemini CLI, and more.",
   "html_url": "https://github.com/Egonex-AI/Understand-Anything",
   "language": "TypeScript",
   "stars": 80159
  },
  {
   "name": "Restormer",
   "owner": "swz30",
   "full_name": "swz30/Restormer",
   "description": "[CVPR 2022--Oral] Restormer: Efficient Transformer for High-Resolution Image Restoration. SOTA  for motion deblurring, image deraining, denoising (Gaussian/real data), and defocus deblurring.",
   "html_url": "https://github.com/swz30/Restormer",
   "language": "Python",
   "stars": 2621
  },
  {
   "name": "sglang",
   "owner": "sgl-project",
   "full_name": "sgl-project/sglang",
   "description": "SGLang is a high-performance serving framework for large language models and multimodal models.",
   "html_url": "https://github.com/sgl-project/sglang",
   "language": "Python",
   "stars": 32279
  },
  {
   "name": "NAFNet",
   "owner": "megvii-research",
   "full_name": "megvii-research/NAFNet",
   "description": "The state-of-the-art image restoration model without nonlinear activation functions.",
   "html_url": "https://github.com/megvii-research/NAFNet",
   "language": "Python",
   "stars": 3146
  },
  {
   "name": "langchain",
   "owner": "langchain-ai",
   "full_name": "langchain-ai/langchain",
   "description": "The agent engineering platform.",
   "html_url": "https://github.com/langchain-ai/langchain",
   "language": "Python",
   "stars": 144811
  },
  {
   "name": "caveman",
   "owner": "JuliusBrussee",
   "full_name": "JuliusBrussee/caveman",
   "description": "🪨 why use many token when few token do trick — Claude Code skill that cuts 65% of tokens by talking like caveman",
   "html_url": "https://github.com/JuliusBrussee/caveman",
   "language": "Go",
   "stars": 100381
  },
  {
   "name": "new-api",
   "owner": "QuantumNous",
   "full_name": "QuantumNous/new-api",
   "description": "A unified AI model hub for aggregation & distribution. It supports cross-converting various LLMs into OpenAI-compatible, Claude-compatible, or Gemini-compatible formats. A centralized gateway for personal and enterprise model management. 🍥",
   "html_url": "https://github.com/QuantumNous/new-api",
   "language": "Go",
   "stars": 45955
  },
  {
   "name": "InfraTech",
   "owner": "CalvinXKY",
   "full_name": "CalvinXKY/InfraTech",
   "description": "分享AI Infra知识&代码练习：PyTorch、vLLM/SGLang、slime/vime框架入门⚡️、性能加速🚀、大模型基础🧠、AI软硬件🔧等",
   "html_url": "https://github.com/CalvinXKY/InfraTech",
   "language": "Jupyter Notebook",
   "stars": 3623
  }
 ],
 "repos": [
  {
   "name": "sunbinbin1991.github.io",
   "description": "Auto-generated GitHub portfolio site · Pages + Actions + API 自动生成个人 GitHub 项目汇总页（定时刷新 · 实时拉取 · 限流回退）",
   "html_url": "https://github.com/sunbinbin1991/sunbinbin1991.github.io",
   "homepage": "",
   "language": "JavaScript",
   "stars": 2,
   "forks": 1,
   "topics": [
    "auto-deploy",
    "github-actions",
    "github-api",
    "github-pages",
    "javascript",
    "personal-website",
    "portfolio",
    "static-site"
   ],
   "created_at": "2026-08-19T09:12:37Z",
   "updated_at": "2026-08-23T02:01:23Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "faceTracker",
   "description": "Open-source face tracking for beginners · faceTracker 入门级人脸跟踪",
   "html_url": "https://github.com/sunbinbin1991/faceTracker",
   "homepage": "",
   "language": "C",
   "stars": 6,
   "forks": 1,
   "topics": [],
   "created_at": "2019-10-27T16:52:55Z",
   "updated_at": "2026-08-21T08:28:49Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "wedding-lottery",
   "description": "Wedding lottery / lucky draw tool (C#)",
   "html_url": "https://github.com/sunbinbin1991/wedding-lottery",
   "homepage": "",
   "language": "C#",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-07-31T16:22:24Z",
   "updated_at": "2026-08-21T08:28:46Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "yinyangFace",
   "description": "Yin-yang face (uneven lighting) quality detection · 阴阳脸检测",
   "html_url": "https://github.com/sunbinbin1991/yinyangFace",
   "homepage": "",
   "language": "Python",
   "stars": 5,
   "forks": 1,
   "topics": [],
   "created_at": "2018-10-30T07:53:14Z",
   "updated_at": "2026-08-21T08:28:44Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "imageRegister",
   "description": "Image capture for registration (C#) · 图片注册采集",
   "html_url": "https://github.com/sunbinbin1991/imageRegister",
   "homepage": "",
   "language": "C#",
   "stars": 2,
   "forks": 1,
   "topics": [],
   "created_at": "2019-02-28T09:53:25Z",
   "updated_at": "2026-08-21T08:28:42Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "quality",
   "description": "Video stream capture & image filter tool (C#, AForge) · 视频流注册照采集过滤小工具",
   "html_url": "https://github.com/sunbinbin1991/quality",
   "homepage": "",
   "language": "C#",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-03-22T11:50:56Z",
   "updated_at": "2026-08-21T08:28:40Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "MyTankwar",
   "description": "A tank war game project",
   "html_url": "https://github.com/sunbinbin1991/MyTankwar",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2016-01-10T08:51:41Z",
   "updated_at": "2026-08-21T08:28:39Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "wife-birthday-website",
   "description": "Birthday greeting website with audio (TypeScript)",
   "html_url": "https://github.com/sunbinbin1991/wife-birthday-website",
   "homepage": "https://wife-birthday-website.vercel.app",
   "language": "TypeScript",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2026-04-16T14:15:35Z",
   "updated_at": "2026-08-21T08:28:39Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "calculator",
   "description": "A simple calculator app for math problems",
   "html_url": "https://github.com/sunbinbin1991/calculator",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 1,
   "topics": [],
   "created_at": "2016-01-19T02:29:54Z",
   "updated_at": "2026-08-21T08:28:38Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "practiceMX",
   "description": "Practice project for MXNet deep learning framework",
   "html_url": "https://github.com/sunbinbin1991/practiceMX",
   "homepage": "",
   "language": "Python",
   "stars": 1,
   "forks": 0,
   "topics": [],
   "created_at": "2018-08-26T07:28:45Z",
   "updated_at": "2026-08-21T08:28:36Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "detect",
   "description": "Face detection demo with dlib (Python)",
   "html_url": "https://github.com/sunbinbin1991/detect",
   "homepage": "",
   "language": "Python",
   "stars": 4,
   "forks": 2,
   "topics": [],
   "created_at": "2017-07-20T12:28:43Z",
   "updated_at": "2026-08-21T08:28:35Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "deepseek-harness",
   "description": "DeepSeek Harness: Everything is a Plugin.",
   "html_url": "https://github.com/sunbinbin1991/deepseek-harness",
   "homepage": "https://deepseek.com/harness",
   "language": "TypeScript",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2026-08-19T00:36:24Z",
   "updated_at": "2026-08-20T05:51:28Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "sunbinbin1991",
   "description": "",
   "html_url": "https://github.com/sunbinbin1991/sunbinbin1991",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2022-05-23T15:21:20Z",
   "updated_at": "2026-08-20T03:37:40Z",
   "fork": false,
   "archived": false,
   "is_profile": true
  },
  {
   "name": "wechat-radar",
   "description": "微信聊天情报看板：聚合群聊信号、话题、链接和趋势",
   "html_url": "https://github.com/sunbinbin1991/wechat-radar",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2026-05-26T04:44:15Z",
   "updated_at": "2026-05-26T04:44:15Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "new-api",
   "description": "A unified AI model hub for aggregation & distribution. It supports cross-converting various LLMs into OpenAI-compatible, Claude-compatible, or Gemini-compatible formats. A centralized gateway for personal and enterprise model management. 🍥",
   "html_url": "https://github.com/sunbinbin1991/new-api",
   "homepage": "https://www.newapi.ai",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2026-04-29T11:44:53Z",
   "updated_at": "2026-04-29T11:44:53Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "claude-code",
   "description": "Claude Code Snapshot for Research. All original source code is the property of Anthropic.",
   "html_url": "https://github.com/sunbinbin1991/claude-code",
   "homepage": "https://x.com/Fried_rice/status/2038894956459290963",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2026-03-31T11:34:37Z",
   "updated_at": "2026-04-02T00:21:52Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "openclaw",
   "description": "Your own personal AI assistant. Any OS. Any Platform. The lobster way. 🦞",
   "html_url": "https://github.com/sunbinbin1991/openclaw",
   "homepage": "https://openclaw.ai",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2026-01-31T09:14:50Z",
   "updated_at": "2026-01-31T09:14:50Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "myfirstcode",
   "description": "myfirstcode",
   "html_url": "https://github.com/sunbinbin1991/myfirstcode",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-10-11T16:29:09Z",
   "updated_at": "2026-01-13T03:30:30Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "faceRec_via_CS-DL",
   "description": "face recognition by dictionary learning",
   "html_url": "https://github.com/sunbinbin1991/faceRec_via_CS-DL",
   "homepage": "",
   "language": "Matlab",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2016-11-01T05:03:52Z",
   "updated_at": "2025-12-16T05:48:39Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "awesome-chatgpt-prompts-zh",
   "description": "ChatGPT 中文调教指南。各种场景使用指南。学习怎么让它听你的话。",
   "html_url": "https://github.com/sunbinbin1991/awesome-chatgpt-prompts-zh",
   "homepage": "https://chat.aimakex.com/",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2023-10-18T03:21:26Z",
   "updated_at": "2023-10-18T03:21:26Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "chatgpt-web",
   "description": "使用 express 和 vue3 搭建的 ChartGPT 演示网页",
   "html_url": "https://github.com/sunbinbin1991/chatgpt-web",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2023-05-27T02:33:33Z",
   "updated_at": "2023-05-27T02:33:33Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "cublas",
   "description": "cublas计算加速",
   "html_url": "https://github.com/sunbinbin1991/cublas",
   "homepage": "",
   "language": "C++",
   "stars": 3,
   "forks": 0,
   "topics": [],
   "created_at": "2018-07-09T13:00:12Z",
   "updated_at": "2022-08-08T15:26:17Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "birthday",
   "description": ":cake:改改数据,为心爱的人做一个超具创意的网页生日祝福吧~ (生日快乐) https://ajlovechina.github.io/birthday/",
   "html_url": "https://github.com/sunbinbin1991/birthday",
   "homepage": "https://ajlovechina.github.io/birthday/",
   "language": "CSS",
   "stars": 1,
   "forks": 0,
   "topics": [],
   "created_at": "2020-12-03T12:18:03Z",
   "updated_at": "2022-04-20T15:30:48Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "Des-Encrypt",
   "description": "一个简单的加密算法",
   "html_url": "https://github.com/sunbinbin1991/Des-Encrypt",
   "homepage": "",
   "language": "C++",
   "stars": 3,
   "forks": 1,
   "topics": [],
   "created_at": "2018-04-13T15:53:07Z",
   "updated_at": "2022-04-05T18:09:42Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "mindspore",
   "description": "MindSpore is a new open source deep learning training/inference framework that could be used for mobile, edge and cloud scenarios.",
   "html_url": "https://github.com/sunbinbin1991/mindspore",
   "homepage": "https://gitee.com/mindspore/mindspore",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2022-02-22T11:36:08Z",
   "updated_at": "2022-02-22T11:36:05Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "samples",
   "description": "",
   "html_url": "https://github.com/sunbinbin1991/samples",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2021-07-17T08:51:04Z",
   "updated_at": "2021-07-17T08:51:04Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "dogecoin",
   "description": "very currency",
   "html_url": "https://github.com/sunbinbin1991/dogecoin",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2021-04-27T11:32:40Z",
   "updated_at": "2021-04-27T11:32:41Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "awesome-computer-vision",
   "description": "A curated list of awesome computer vision resources",
   "html_url": "https://github.com/sunbinbin1991/awesome-computer-vision",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2021-04-08T15:50:23Z",
   "updated_at": "2021-04-08T15:50:24Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "avatarify-python",
   "description": "Avatars for Zoom, Skype and other video-conferencing apps.",
   "html_url": "https://github.com/sunbinbin1991/avatarify-python",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2021-03-11T01:57:28Z",
   "updated_at": "2021-03-11T01:57:29Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "HelloGitHub",
   "description": ":octocat: Find pearls on open-source seashore 分享 GitHub 上有趣、入门级的开源项目",
   "html_url": "https://github.com/sunbinbin1991/HelloGitHub",
   "homepage": "https://hellogithub.com/",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2021-03-11T01:49:59Z",
   "updated_at": "2021-03-11T01:50:01Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "coder2gwy",
   "description": "互联网首份程序员考公指南，由3位已经进入体制内的前大厂程序员联合献上。",
   "html_url": "https://github.com/sunbinbin1991/coder2gwy",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2021-01-13T11:16:31Z",
   "updated_at": "2021-01-13T11:16:33Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "fucking-algorithm",
   "description": "刷算法全靠套路，认准 labuladong 就够了！English version supported! Crack LeetCode, not only how, but also why.",
   "html_url": "https://github.com/sunbinbin1991/fucking-algorithm",
   "homepage": "https://labuladong.gitbook.io/algo/",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2020-10-16T16:06:09Z",
   "updated_at": "2020-10-16T16:06:11Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "SDC-NNIE-tutorial",
   "description": "华为海思hi系列芯片使用的NNIE推理框架教程",
   "html_url": "https://github.com/sunbinbin1991/SDC-NNIE-tutorial",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2020-10-16T16:03:10Z",
   "updated_at": "2020-10-16T16:03:12Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "TNN",
   "description": "TNN：由腾讯优图实验室打造，移动端高性能、轻量级推理框架，同时拥有跨平台、高性能、模型压缩、代码裁剪等众多突出优势。TNN框架在原有Rapidnet、ncnn框架的基础上进一步加强了移动端设备的支持以及性能优化，同时也借鉴了业界主流开源框架高性能和良好拓展性的优点。目前TNN已经在手Q、微视、P图等应用中落地，欢迎大家参与协同共建，促进TNN推理框架进一步完善。",
   "html_url": "https://github.com/sunbinbin1991/TNN",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2020-06-11T02:05:14Z",
   "updated_at": "2020-06-11T02:05:15Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "pose-animator",
   "description": "",
   "html_url": "https://github.com/sunbinbin1991/pose-animator",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2020-05-12T23:40:00Z",
   "updated_at": "2020-05-12T23:40:02Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "logo-detect",
   "description": "TV logo-detect",
   "html_url": "https://github.com/sunbinbin1991/logo-detect",
   "homepage": "",
   "language": "Python",
   "stars": 3,
   "forks": 2,
   "topics": [],
   "created_at": "2017-07-26T13:16:10Z",
   "updated_at": "2020-04-24T07:42:03Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "paper",
   "description": "Include my paper",
   "html_url": "https://github.com/sunbinbin1991/paper",
   "homepage": "",
   "language": "",
   "stars": 2,
   "forks": 0,
   "topics": [],
   "created_at": "2017-07-14T09:09:44Z",
   "updated_at": "2020-03-20T01:42:24Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "cvpr2020",
   "description": "cvpr2020/cvpr2019／cvpr2018/cvpr2017 papers，极市团队整理",
   "html_url": "https://github.com/sunbinbin1991/cvpr2020",
   "homepage": "http://bbs.cvmart.net/",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2020-03-01T04:49:14Z",
   "updated_at": "2020-03-01T04:49:16Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "openssl_for_ios_and_android",
   "description": "OpenSSL Library for iOS and Android",
   "html_url": "https://github.com/sunbinbin1991/openssl_for_ios_and_android",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-12-20T15:55:34Z",
   "updated_at": "2019-12-20T15:55:35Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "MNN",
   "description": "MNN is a lightweight deep neural network inference engine.",
   "html_url": "https://github.com/sunbinbin1991/MNN",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-11-26T15:38:32Z",
   "updated_at": "2019-11-26T15:38:33Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "ThreadPool",
   "description": "A simple C++11 Thread Pool implementation",
   "html_url": "https://github.com/sunbinbin1991/ThreadPool",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-11-05T16:02:34Z",
   "updated_at": "2019-11-05T16:02:39Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "ZQCNN",
   "description": "一款比mini-caffe更快的Forward库，觉得好用请点星啊，400星公布快速人脸检测模型，500星公布106点landmark，600星公布人头检测模型，700星公布人脸检测套餐（六种pnet,两种rnet随意混合使用满足各种速度/精度要求），800星公布更准的106点模型",
   "html_url": "https://github.com/sunbinbin1991/ZQCNN",
   "homepage": "",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-10-27T15:46:05Z",
   "updated_at": "2019-10-27T15:46:06Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "Multitarget-tracker",
   "description": "Multiple Object Tracker, Based on  Hungarian algorithm + Kalman filter.",
   "html_url": "https://github.com/sunbinbin1991/Multitarget-tracker",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-10-26T16:28:32Z",
   "updated_at": "2019-10-27T14:30:37Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "FaceTrack_ncnn_HyperFT",
   "description": "使用mtcnn和o网络跟踪+光流跟踪进行多目标人脸跟踪，单目标人脸光流跟踪是0.5ms左右",
   "html_url": "https://github.com/sunbinbin1991/FaceTrack_ncnn_HyperFT",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-10-26T02:55:00Z",
   "updated_at": "2019-10-26T09:16:51Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "zh-google-styleguide",
   "description": "Google 开源项目风格指南 (中文版)",
   "html_url": "https://github.com/sunbinbin1991/zh-google-styleguide",
   "homepage": "http://zh-google-styleguide.readthedocs.org/",
   "language": "Makefile",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-10-23T12:25:11Z",
   "updated_at": "2019-10-23T12:27:38Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "awesome-cpp",
   "description": "A curated list of awesome C++ (or C) frameworks, libraries, resources, and shiny things. Inspired by awesome-... stuff.",
   "html_url": "https://github.com/sunbinbin1991/awesome-cpp",
   "homepage": "http://fffaraz.github.io/awesome-cpp/",
   "language": "",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-08-29T01:59:02Z",
   "updated_at": "2019-08-29T01:59:04Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "Tengine",
   "description": "Tengine is a lite, high performance, modular inference engine for embedded device",
   "html_url": "https://github.com/sunbinbin1991/Tengine",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-04-04T03:39:04Z",
   "updated_at": "2019-04-04T03:39:08Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "opencv",
   "description": "Open Source Computer Vision Library",
   "html_url": "https://github.com/sunbinbin1991/opencv",
   "homepage": "https://opencv.org",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2019-01-07T12:28:50Z",
   "updated_at": "2019-01-07T12:29:03Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "free-programming-books-zh_CN",
   "description": ":books: 免费的计算机编程类中文书籍，欢迎投稿",
   "html_url": "https://github.com/sunbinbin1991/free-programming-books-zh_CN",
   "homepage": "http://weibo.com/justjavac",
   "language": "JavaScript",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2018-04-22T16:29:43Z",
   "updated_at": "2018-04-22T16:29:46Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "CodeRepository",
   "description": "CodeRepository这个项目主要用来建立常见的数据结构代码、算法代码和并行、网络等代码库，方便后面开发的重复使用。",
   "html_url": "https://github.com/sunbinbin1991/CodeRepository",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2018-03-30T01:12:29Z",
   "updated_at": "2018-03-30T01:12:30Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "hangzhou_house_knowledge",
   "description": "2017年买房经历总结出来的买房购房知识分享给大家，希望对大家有所帮助。买房不易，且买且珍惜。Sharing the knowledge of buy an own house that according  to the experience at hangzhou in 2017 to all the people. It's not easy to buy a own house, so I hope that it would be useful to everyone.",
   "html_url": "https://github.com/sunbinbin1991/hangzhou_house_knowledge",
   "homepage": "",
   "language": "CSS",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2018-03-23T15:21:11Z",
   "updated_at": "2018-03-23T15:21:14Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "wedding",
   "description": "婚礼大屏互动，微信请柬一站式解决方案",
   "html_url": "https://github.com/sunbinbin1991/wedding",
   "homepage": "",
   "language": "JavaScript",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2018-02-28T05:36:18Z",
   "updated_at": "2018-02-28T05:36:20Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "ncnn-bin",
   "description": "reference",
   "html_url": "https://github.com/sunbinbin1991/ncnn-bin",
   "homepage": "https://github.com/Tencent/ncnn",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2018-01-19T11:53:24Z",
   "updated_at": "2018-01-19T12:01:17Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "deeplearning.ai",
   "description": "deeplearning.ai , By Andrew Ng, All slide and notebook + data (without solution) and video link",
   "html_url": "https://github.com/sunbinbin1991/deeplearning.ai",
   "homepage": "",
   "language": "HTML",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2017-12-13T16:22:41Z",
   "updated_at": "2017-12-13T16:22:47Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "age-gender-estimation",
   "description": "Keras implementation of a CNN network for age and gender estimation",
   "html_url": "https://github.com/sunbinbin1991/age-gender-estimation",
   "homepage": "",
   "language": "Jupyter Notebook",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2017-11-28T02:44:14Z",
   "updated_at": "2017-11-28T02:44:15Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "ncnn",
   "description": "ncnn is a high-performance neural network inference framework optimized for the mobile platform",
   "html_url": "https://github.com/sunbinbin1991/ncnn",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2017-11-18T01:38:10Z",
   "updated_at": "2017-11-18T01:38:12Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "ncnn-mobile",
   "description": "use ncnn in Android(Android Studio) and iOS",
   "html_url": "https://github.com/sunbinbin1991/ncnn-mobile",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2017-11-16T14:29:16Z",
   "updated_at": "2017-11-16T14:29:18Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "MTCNN-light",
   "description": "this repository is the implementation of MTCNN with no framework,  Just need opencv and openblas, support linux and windows",
   "html_url": "https://github.com/sunbinbin1991/MTCNN-light",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2017-11-07T09:05:28Z",
   "updated_at": "2017-11-07T09:05:30Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "OpenPose",
   "description": "OpenPose的简单实现版本，简洁不简单，so easy. 就一个cpp",
   "html_url": "https://github.com/sunbinbin1991/OpenPose",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2017-11-04T11:54:26Z",
   "updated_at": "2017-11-04T11:54:29Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "xml2txt",
   "description": "just change xml to txt file",
   "html_url": "https://github.com/sunbinbin1991/xml2txt",
   "homepage": "",
   "language": "Python",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2017-10-21T10:33:21Z",
   "updated_at": "2017-10-21T11:03:05Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "MobileNet_Mxnet",
   "description": "This is an Mxnet implementation of \"MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications\"",
   "html_url": "https://github.com/sunbinbin1991/MobileNet_Mxnet",
   "homepage": "",
   "language": "Python",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2017-05-15T08:21:03Z",
   "updated_at": "2017-05-15T08:21:05Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "SeetaFaceEngine",
   "description": "",
   "html_url": "https://github.com/sunbinbin1991/SeetaFaceEngine",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2016-10-07T06:09:47Z",
   "updated_at": "2016-10-07T06:09:49Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "Python_headDetect",
   "description": "使用Python完成的头部检测程序",
   "html_url": "https://github.com/sunbinbin1991/Python_headDetect",
   "homepage": "",
   "language": "Python",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2016-07-14T13:20:19Z",
   "updated_at": "2016-07-14T13:57:16Z",
   "fork": false,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "herodb",
   "description": "Database engine which is either RDBMS or GraphDB",
   "html_url": "https://github.com/sunbinbin1991/herodb",
   "homepage": "",
   "language": "C++",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2016-04-07T12:53:02Z",
   "updated_at": "2016-04-07T12:53:04Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "jfinal",
   "description": "JAVA WEB + ORM Framework",
   "html_url": "https://github.com/sunbinbin1991/jfinal",
   "homepage": "http://www.jfinal.com",
   "language": "Java",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2016-04-07T12:52:31Z",
   "updated_at": "2016-04-07T12:52:32Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  },
  {
   "name": "golo-lang",
   "description": "Golo - a lightweight dynamic language for the JVM.",
   "html_url": "https://github.com/sunbinbin1991/golo-lang",
   "homepage": "http://golo-lang.org/",
   "language": "Java",
   "stars": 0,
   "forks": 0,
   "topics": [],
   "created_at": "2016-04-07T12:49:17Z",
   "updated_at": "2016-04-07T12:49:19Z",
   "fork": true,
   "archived": false,
   "is_profile": false
  }
 ]
};
